version: "3"
services:
  db1:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: transactions
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  runner:
    build:
      context: .
      target: runner
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: db1
      MYSQL_PORT: 3306
      MYSQL_DATABASE: transactions
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

volumes:
  db_data:
